name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Install Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }}
    strategy:
      matrix:
        otp: ["24.2.1"]
        elixir: ["1.13.3-otp-24"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1.1.0
      - name: asdf cache
        uses: actions/cache@v2
        with:
          path: ${{ env.ASDF_DIR }}
          key: ${{ runner.os }}-asdf-v3-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}
          restore-keys: |
            ${{ runner.os }}-asdf-v3-otp-${{ matrix.otp }}-elixir-${{ matrix.elixir }}
            ${{ runner.os }}-asdf-v3-otp-${{ matrix.otp }}-
            ${{ runner.os }}-asdf-v3-
      - name: install asdf plugins
        uses: asdf-vm/actions/plugins-add@v1.1.0
      - name: asdf install
        uses: asdf-vm/actions/install@v1.1.0

      - run: elixir --version
      - run: brew install portmidi
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix test
